### ISSUE TITLE
Tooltips - Infobulles - les rendre responsive

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Stromae#264]
🇫🇷 
Actuellement, le contenu de l'infobulle s'affiche sur une ligne unique, donc si le contenu est trop riche, une partie de l'infobulle est tronquée

**Comment by romaintailhurat** [comment]
Une piste de solution en CSS:

```css
.__react_component_tooltip.show { 
    opacity: 0.9;
    margin-top: 0;
    margin-left: 0;
    visibility: visible;
   /* adding these two fields */
    inline-size: 300px;
    overflow-wrap: break-word; }
```
